name: mh_care
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  cloud_firestore: ^2.4.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  firebase_storage: ^10.0.1
  intl: ^0.17.0
  provider: ^5.0.0
  toggle_switch: ^1.2.0
  image_picker: ^0.8.2
  permission_handler: ^8.1.2
  file_picker: ^3.0.3
  cached_network_image: ^3.1.0
  flutter_cached_pdfview: 0.4.0-nullsafety
  get: ^4.1.4
  flutter_swiper: ^1.1.6
  google_fonts: ^2.1.0
  email_validator: ^2.0.1
  modal_progress_hud: ^0.1.3
  json_annotation: 3.1.1
#  flutter_native_splash: ^1.2.0
#  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  build_runner:
  json_serializable: 3.5.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appIcon.png"
  adaptive_icon_background: "#FFFFFF"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/intro/

    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
